"""IR → standalone Python solver script."""

from __future__ import annotations

import ast
import re
from md2mip.ir import IR, Constraint, Variable


def generate(ir: IR) -> str:
    """Generate a standalone Python solver script from an IR."""
    ir.validate()
    parts = [
        _header(ir),
        _load_data(ir),
        _build_model(ir),
        *_constraint_functions(ir),
        _solve_and_report(ir),
        _main(),
    ]
    return "\n\n".join(parts) + "\n"


# ---------------------------------------------------------------------------
# Variable layout helpers
# ---------------------------------------------------------------------------

def _var_layout(ir: IR) -> list[tuple[str, Variable, str]]:
    """Return (name, var, offset_expr) for each variable group in flat index order."""
    layout = []
    for name, var in ir.variables.items():
        layout.append((name, var, _offset_expr(name, ir)))
    return layout


def _var_size_expr(var: Variable, ir: IR) -> str:
    """Return a Python expression for the number of elements in a variable group."""
    if not var.indices:
        return "1"
    parts = [f"n_{s.lower()}" for s in var.indices]
    return " * ".join(parts)


def _total_vars_expr(ir: IR) -> str:
    parts = []
    for name, var in ir.variables.items():
        parts.append(_var_size_expr(var, ir))
    return " + ".join(parts)


# ---------------------------------------------------------------------------
# Code sections
# ---------------------------------------------------------------------------

def _header(ir: IR) -> str:
    return f'''#!/usr/bin/env python3
"""{ir.name} model — generated by md2mip"""

import argparse
import json
import sys

import highspy
import numpy as np
import yaml'''


def _load_data(ir: IR) -> str:
    lines = [
        'def load_data(path: str) -> dict:',
        '    """Load data from YAML or JSON into numpy arrays."""',
        '    with open(path) as f:',
        '        if path.endswith(".json"):',
        '            raw = json.load(f)',
        '        else:',
        '            raw = yaml.safe_load(f)',
        '    data = {}',
    ]
    for sname in ir.sets:
        lines.append(f'    data["{sname}"] = list(raw["{sname}"])')
    for pname, param in ir.parameters.items():
        if param.indices:
            lines.append(f'    data["{pname}"] = np.array(raw["{pname}"], dtype=np.float64)')
        else:
            if param.default is not None:
                lines.append(f'    data["{pname}"] = float(raw.get("{pname}", {param.default}))')
            else:
                lines.append(f'    data["{pname}"] = float(raw["{pname}"])')
    lines.append('    return data')
    return "\n".join(lines)


def _build_model(ir: IR) -> str:
    lines = ['def build_model(data: dict) -> highspy.Highs:']

    # Set sizes
    for sname in ir.sets:
        lines.append(f'    n_{sname.lower()} = len(data["{sname}"])')

    lines.append('')
    lines.append('    h = highspy.Highs()')
    lines.append('    h.silent()')
    lines.append('')

    # Total variables
    n_vars_expr = _total_vars_expr(ir)
    lines.append(f'    n_vars = {n_vars_expr}')
    lines.append('')

    # Add variables
    layout = _var_layout(ir)
    for vname, var, _offset in layout:
        size_expr = _var_size_expr(var, ir)
        lb = var.lower_bound if var.lower_bound is not None else 0
        ub_val = var.upper_bound
        if var.type == "binary":
            lb, ub_val = 0, 1
        lb_str = f"np.zeros({size_expr})" if lb == 0 else f"np.full({size_expr}, {lb})"
        if ub_val is None:
            ub_str = f"np.full({size_expr}, np.inf)"
        else:
            ub_str = f"np.full({size_expr}, {ub_val})"
        lines.append(f'    # --- Variable: {vname}{_index_comment(var)} ---')
        lines.append(f'    h.addVars({size_expr}, {lb_str}, {ub_str})')
        if var.type == "binary":
            offset_expr = _offset_expr(vname, ir)
            lines.append(f'    for _k in range({size_expr}):')
            lines.append(f'        h.changeColIntegrality({offset_expr} + _k, highspy.HighsVarType.kInteger)')

    lines.append('')

    # Objective
    lines.append('    # --- Objective ---')
    obj = ir.objective
    obj_code = _generate_objective(obj.expression, ir)
    lines.extend(f'    {l}' for l in obj_code)
    sense = "kMinimize" if obj.sense == "minimize" else "kMaximize"
    lines.append(f'    h.changeObjectiveSense(highspy.ObjSense.{sense})')
    lines.append('')

    # Constraint groups
    for cname in ir.constraints:
        fn_name = f"setup_{cname}_constraints"
        args = _constraint_fn_args(ir)
        lines.append(f'    {fn_name}({args})')

    lines.append('')
    lines.append('    return h')
    return "\n".join(lines)


def _index_comment(var: Variable) -> str:
    if not var.indices:
        return ""
    idx = ",".join(s.lower() for s in var.indices)
    return f"[{idx}]"


def _offset_expr(vname: str, ir: IR) -> str:
    """Return a Python expression for the flat offset of variable group vname."""
    offset_parts = []
    for name, var in ir.variables.items():
        if name == vname:
            break
        offset_parts.append(_var_size_expr(var, ir))
    if not offset_parts:
        return "0"
    return " + ".join(offset_parts)


def _constraint_fn_args(ir: IR) -> str:
    parts = ["h", "data"]
    for sname in ir.sets:
        parts.append(f"n_{sname.lower()}")
    return ", ".join(parts)


def _parse_comparison(expr_str: str) -> tuple[str, str, str]:
    """Split 'lhs <= rhs' into (lhs, op, rhs). Also handles >=, ==."""
    for op in ("<=", ">=", "=="):
        if op in expr_str:
            parts = expr_str.split(op, 1)
            return parts[0].strip(), op, parts[1].strip()
    raise ValueError(f"No comparison operator found in: {expr_str}")


# ---------------------------------------------------------------------------
# Objective code generation
# ---------------------------------------------------------------------------

def _generate_objective(expr: str, ir: IR) -> list[str]:
    """Generate code to set objective coefficients."""
    lines = []
    lines.append(f"obj_coeffs = np.zeros(n_vars)")

    # Parse the objective expression to find sum(coeff * var for ...)
    # We handle: sum(p[i]*x[i] ...) and sum(f[i]*y[i] ...) + sum(c[i,j]*x[i,j] ...)
    terms = _split_top_level_sums(expr)
    for term in terms:
        lines.extend(_gen_obj_term(term, ir))

    lines.append("h.changeColsCost(n_vars, np.arange(n_vars, dtype=np.int32), obj_coeffs)")
    return lines


def _split_top_level_sums(expr: str) -> list[str]:
    """Split 'sum(...) + sum(...)' into individual sum expressions."""
    # Find top-level + between sum() calls
    results = []
    depth = 0
    current = []
    i = 0
    while i < len(expr):
        ch = expr[i]
        if ch == '(':
            depth += 1
            current.append(ch)
        elif ch == ')':
            depth -= 1
            current.append(ch)
        elif ch == '+' and depth == 0:
            results.append("".join(current).strip())
            current = []
        else:
            current.append(ch)
        i += 1
    if current:
        results.append("".join(current).strip())
    return [r for r in results if r]


def _gen_obj_term(term: str, ir: IR) -> list[str]:
    """Generate code for one sum(...) term in the objective."""
    lines = []
    # Parse: sum(body for idx1 in Set1 for idx2 in Set2)
    m = re.match(r'sum\((.+)\)', term, re.DOTALL)
    if not m:
        # Scalar term like "K * z[t]" — shouldn't normally appear at top level
        return [f"# TODO: non-sum objective term: {term}"]

    inner = m.group(1).strip()

    # Split off 'for ...' clauses
    body, iterators = _split_body_and_iterators(inner)

    # Parse iterators: "i in I", "j in J"
    idx_vars = []
    idx_sets = []
    for it in iterators:
        parts = it.strip().split(" in ")
        idx_vars.append(parts[0].strip())
        idx_sets.append(parts[1].strip())

    # The body might have multiple additive terms: p * x[t] + h * Inv[t] + K * z[t]
    # Split into individual terms and handle each
    body_terms = _split_additive_terms(body)

    # Generate nested loop
    indent = ""
    for iv, iset in zip(idx_vars, idx_sets):
        size = f"n_{iset.lower()}"
        lines.append(f"{indent}for {iv} in range({size}):")
        indent += "    "

    for sign, bterm in body_terms:
        bterm = bterm.strip()
        coeff_expr, var_name, var_indices = _parse_product(bterm, ir)
        if var_name not in ir.variables:
            lines.append(f"{indent}# TODO: non-variable term: {bterm}")
            continue

        offset = _offset_expr(var_name, ir)
        flat_idx = _flat_index_expr(var_name, var_indices, ir)
        effective_coeff = coeff_expr if sign == "+" else _negate(coeff_expr)
        lines.append(f"{indent}obj_coeffs[{offset} + {flat_idx}] += {_coeff_code(effective_coeff, ir)}")

    return lines


def _split_body_and_iterators(inner: str) -> tuple[str, list[str]]:
    """Split 'coeff * var for i in I for j in J' into body and iterator list."""
    # Find first ' for ' that's not inside brackets
    parts = re.split(r'\s+for\s+', inner)
    body = parts[0]
    iterators = parts[1:]
    return body, iterators


def _parse_product(body: str, ir: IR) -> tuple[str, str, list[str]]:
    """Parse 'c[i,j] * x[i,j]' into (coeff_expr, var_name, var_indices).

    Also handles: 'x[i,j]' (coeff=1), 'p * x[t]' (scalar param * var).
    """
    body = body.strip()

    # Try to parse as AST
    tree = ast.parse(body, mode='eval')
    node = tree.body

    return _extract_product(node, ir)


def _extract_product(node: ast.expr, ir: IR) -> tuple[str, str, list[str]]:
    """Extract (coeff_source, var_name, var_indices) from an AST node."""
    if isinstance(node, ast.BinOp) and isinstance(node.op, ast.Mult):
        # A * B — figure out which side is the variable
        left_var = _find_var_ref(node.left, ir)
        right_var = _find_var_ref(node.right, ir)

        if right_var:
            vname, vindices = right_var
            coeff = ast.unparse(node.left)
            return coeff, vname, vindices
        elif left_var:
            vname, vindices = left_var
            coeff = ast.unparse(node.right)
            return coeff, vname, vindices
    elif isinstance(node, ast.Subscript):
        vref = _find_var_ref(node, ir)
        if vref:
            return "1", vref[0], vref[1]

    # Fallback
    return ast.unparse(node), "_unknown", []


def _find_var_ref(node: ast.expr, ir: IR) -> tuple[str, list[str]] | None:
    """If node is var[i,j], return (var_name, [i, j])."""
    if isinstance(node, ast.Subscript) and isinstance(node.value, ast.Name):
        name = node.value.id
        if name in ir.variables:
            indices = _extract_subscript_indices(node.slice)
            return name, indices
    return None


def _extract_subscript_indices(node: ast.expr) -> list[str]:
    """Extract index names from a subscript: x[i,j] -> ['i', 'j'], x[i] -> ['i']."""
    if isinstance(node, ast.Tuple):
        return [ast.unparse(e) for e in node.elts]
    return [ast.unparse(node)]


def _flat_index_expr(var_name: str, indices: list[str], ir: IR) -> str:
    """Compute flat index expression for var[i,j,...] given the variable's index sets."""
    var = ir.variables[var_name]
    if len(indices) == 0:
        return "0"
    if len(indices) == 1:
        return indices[0]
    # Row-major: i * n_j + j for indices [i, j] with sets [I, J]
    # General: idx[0] * prod(sizes[1:]) + idx[1] * prod(sizes[2:]) + ... + idx[-1]
    sizes = [f"n_{s.lower()}" for s in var.indices]
    parts = []
    for k, idx in enumerate(indices):
        if k < len(indices) - 1:
            suffix = " * ".join(sizes[k + 1:])
            parts.append(f"{idx} * {suffix}")
        else:
            parts.append(idx)
    return " + ".join(parts)


def _coeff_code(coeff_expr: str, ir: IR) -> str:
    """Convert a coefficient expression to Python code referencing data dict."""
    if coeff_expr == "1":
        return "1.0"
    # Replace param references: c[i,j] -> data["c"][i,j], p -> data["p"]
    tree = ast.parse(coeff_expr, mode='eval')
    return _coeff_node_to_code(tree.body, ir)


def _coeff_node_to_code(node: ast.expr, ir: IR) -> str:
    """Convert an AST node for a coefficient to Python code."""
    if isinstance(node, ast.Subscript) and isinstance(node.value, ast.Name):
        name = node.value.id
        if name in ir.parameters:
            indices = _extract_subscript_indices(node.slice)
            idx_str = ", ".join(indices)
            return f'data["{name}"][{idx_str}]'
    if isinstance(node, ast.Name):
        name = node.id
        if name in ir.parameters:
            return f'data["{name}"]'
    if isinstance(node, ast.BinOp):
        left = _coeff_node_to_code(node.left, ir)
        right = _coeff_node_to_code(node.right, ir)
        op_map = {ast.Add: '+', ast.Sub: '-', ast.Mult: '*', ast.Div: '/'}
        op_str = op_map.get(type(node.op), '+')
        return f"({left} {op_str} {right})"
    if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.USub):
        inner = _coeff_node_to_code(node.operand, ir)
        return f"-({inner})"
    if isinstance(node, ast.Constant):
        return repr(node.value)
    # Fallback
    return ast.unparse(node)


# ---------------------------------------------------------------------------
# Constraint code generation
# ---------------------------------------------------------------------------

def _constraint_functions(ir: IR) -> list[str]:
    results = []
    for cname, constraint in ir.constraints.items():
        results.append(_gen_constraint_fn(cname, constraint, ir))
    return results


def _gen_constraint_fn(cname: str, constraint: Constraint, ir: IR) -> str:
    params = _constraint_fn_args(ir)
    lines = [
        f'def setup_{cname}_constraints({params}):',
        f'    """{constraint.expression}"""',
    ]

    # Parse the constraint expression
    lhs_str, op, rhs_str = _parse_comparison(constraint.expression)

    # Determine iteration space
    idx_vars, idx_sets = _parse_for_all(constraint.for_all)

    # Check for special case: lag references (t-1)
    has_lag = "t-1" in constraint.expression or "t - 1" in constraint.expression

    if has_lag and not constraint.for_all:
        # Single constraint with lag reference at t=0 (balance_first)
        lines.extend(_gen_single_constraint_with_lag(lhs_str, op, rhs_str, constraint, ir))
    elif has_lag:
        # Constraint with lag — needs special handling, generate with loops
        lines.extend(_gen_lag_constraint(lhs_str, op, rhs_str, idx_vars, idx_sets, constraint, ir))
    elif not constraint.for_all:
        # Single constraint (no for_all)
        lines.extend(_gen_single_constraint(lhs_str, op, rhs_str, ir))
    else:
        # Normal constraint group with for_all
        lines.extend(_gen_normal_constraint(cname, lhs_str, op, rhs_str, idx_vars, idx_sets, ir))

    return "\n".join(lines)


def _parse_for_all(for_all: list[str]) -> tuple[list[str], list[str]]:
    idx_vars = []
    idx_sets = []
    for fa in for_all:
        parts = fa.split(" in ")
        idx_vars.append(parts[0].strip())
        idx_sets.append(parts[1].strip())
    return idx_vars, idx_sets


def _gen_single_constraint(lhs_str: str, op: str, rhs_str: str, ir: IR) -> list[str]:
    """Generate a single constraint (no for_all)."""
    lines = []

    # Analyze both sides for variable terms
    lhs_terms = _extract_linear_terms(lhs_str, ir)
    rhs_terms = _extract_linear_terms(rhs_str, ir)

    # Move all variable terms to LHS, constant terms to RHS
    # var_terms: list of (coeff_code, var_name, var_indices, iterators)
    # const_terms: list of code strings
    all_var_terms = lhs_terms["var_terms"] + [(_negate(c), v, vi, it) for c, v, vi, it in rhs_terms["var_terms"]]
    rhs_const = rhs_terms["const_terms"] + [f"-({c})" for c in lhs_terms["const_terms"]]

    lines.append("    # Build row as a list of (col_index, coefficient)")
    lines.append("    row_indices = []")
    lines.append("    row_values = []")

    for coeff, vname, vindices, iterators in all_var_terms:
        offset = _offset_expr(vname, ir)
        if iterators:
            indent = "    "
            for iv, iset in iterators:
                lines.append(f"{indent}for {iv} in range(n_{iset.lower()}):")
                indent += "    "
            flat = _flat_index_expr(vname, vindices, ir)
            coeff_c = _coeff_code(coeff, ir)
            lines.append(f"{indent}row_indices.append({offset} + {flat})")
            lines.append(f"{indent}row_values.append({coeff_c})")
        else:
            flat = _flat_index_expr(vname, vindices, ir)
            coeff_c = _coeff_code(coeff, ir)
            lines.append(f"    row_indices.append({offset} + {flat})")
            lines.append(f"    row_values.append({coeff_c})")

    rhs_code = " + ".join(rhs_const) if rhs_const else "0"
    rhs_code = _substitute_params(rhs_code, ir)
    lb, ub = _bounds_from_op(op, rhs_code)

    lines.append(f"    row_lower = np.array([{lb}])")
    lines.append(f"    row_upper = np.array([{ub}])")
    lines.append("    starts = np.array([0, len(row_indices)], dtype=np.int32)")
    lines.append("    h.addRows(1, row_lower, row_upper, len(row_indices),")
    lines.append("              starts, np.array(row_indices, dtype=np.int32),")
    lines.append("              np.array(row_values, dtype=np.float64))")

    return lines


def _gen_normal_constraint(cname: str, lhs_str: str, op: str, rhs_str: str,
                           idx_vars: list[str], idx_sets: list[str], ir: IR) -> list[str]:
    """Generate a constraint group with for_all — one addRows call per iteration."""
    lines = []

    # For multi-index for_all (e.g., i in I, j in J), we generate nested loops
    # and add one row per iteration
    lines.append("    all_row_lower = []")
    lines.append("    all_row_upper = []")
    lines.append("    all_indices = []")
    lines.append("    all_values = []")
    lines.append("    starts = [0]")

    indent = "    "
    for iv, iset in zip(idx_vars, idx_sets):
        lines.append(f"{indent}for {iv} in range(n_{iset.lower()}):")
        indent += "    "

    # Inside the loop, parse expression and emit row construction
    lhs_terms = _extract_linear_terms(lhs_str, ir)
    rhs_terms = _extract_linear_terms(rhs_str, ir)

    all_var_terms = lhs_terms["var_terms"] + [(_negate(c), v, vi, it) for c, v, vi, it in rhs_terms["var_terms"]]
    rhs_const = rhs_terms["const_terms"] + [f"-({c})" for c in lhs_terms["const_terms"]]

    lines.append(f"{indent}row_idx = []")
    lines.append(f"{indent}row_val = []")

    for coeff, vname, vindices, iterators in all_var_terms:
        offset = _offset_expr(vname, ir)
        inner_indent = indent
        if iterators:
            # Filter out iterators that are already covered by for_all
            remaining = [(iv, iset) for iv, iset in iterators if iv not in idx_vars]
            for iv, iset in remaining:
                lines.append(f"{inner_indent}for {iv} in range(n_{iset.lower()}):")
                inner_indent += "    "

        flat = _flat_index_expr(vname, vindices, ir)
        coeff_c = _coeff_code(coeff, ir)
        lines.append(f"{inner_indent}row_idx.append({offset} + {flat})")
        lines.append(f"{inner_indent}row_val.append({coeff_c})")

    rhs_code = " + ".join(rhs_const) if rhs_const else "0"
    rhs_code = _substitute_params(rhs_code, ir)
    lb, ub = _bounds_from_op(op, rhs_code)

    lines.append(f"{indent}all_row_lower.append({lb})")
    lines.append(f"{indent}all_row_upper.append({ub})")
    lines.append(f"{indent}all_indices.extend(row_idx)")
    lines.append(f"{indent}all_values.extend(row_val)")
    lines.append(f"{indent}starts.append(len(all_indices))")

    lines.append("    n_cons = len(all_row_lower)")
    lines.append("    h.addRows(n_cons, np.array(all_row_lower), np.array(all_row_upper),")
    lines.append("              len(all_indices), np.array(starts, dtype=np.int32),")
    lines.append("              np.array(all_indices, dtype=np.int32),")
    lines.append("              np.array(all_values, dtype=np.float64))")

    return lines


def _gen_lag_constraint(lhs_str: str, op: str, rhs_str: str,
                        idx_vars: list[str], idx_sets: list[str],
                        constraint: Constraint, ir: IR) -> list[str]:
    """Generate constraints with lag references like Inv[t-1]."""
    lines = []

    # For lag constraints, we skip t=0 (handled by balance_first) and iterate t=1..T-1
    lines.append("    all_row_lower = []")
    lines.append("    all_row_upper = []")
    lines.append("    all_indices = []")
    lines.append("    all_values = []")
    lines.append("    starts = [0]")

    # Check if there's a separate _first constraint — if so start from 1
    has_first = any("_first" in cn for cn in ir.constraints)

    start_idx = "1" if has_first else "0"
    indent = "    "
    for iv, iset in zip(idx_vars, idx_sets):
        lines.append(f"{indent}for {iv} in range({start_idx}, n_{iset.lower()}):")
        indent += "    "

    # Parse the expression, handling t-1 references
    # e.g., Inv[t] == Inv[t-1] + x[t] - d[t]
    # becomes: Inv[t] - Inv[t-1] - x[t] == -d[t]
    # which means: coeff 1 for Inv[t], coeff -1 for Inv[t-1], coeff -1 for x[t], rhs = -d[t]

    lines.append(f"{indent}row_idx = []")
    lines.append(f"{indent}row_val = []")

    # Parse both sides
    lhs_terms = _extract_linear_terms_with_lags(lhs_str, ir)
    rhs_terms = _extract_linear_terms_with_lags(rhs_str, ir)

    all_var_terms = lhs_terms["var_terms"] + [(_negate(c), v, vi, it, lag) for c, v, vi, it, lag in rhs_terms["var_terms"]]
    rhs_const = rhs_terms["const_terms"] + [f"-({c})" for c in lhs_terms["const_terms"]]

    for coeff, vname, vindices, iterators, lag in all_var_terms:
        offset = _offset_expr(vname, ir)
        # Adjust index for lag
        adjusted_indices = []
        for idx in vindices:
            if lag and idx == idx_vars[0]:  # primary iterator with lag
                adjusted_indices.append(f"{idx} - {lag}")
            else:
                adjusted_indices.append(idx)
        flat = _flat_index_expr(vname, adjusted_indices, ir)
        coeff_c = _coeff_code(coeff, ir)
        lines.append(f"{indent}row_idx.append({offset} + {flat})")
        lines.append(f"{indent}row_val.append({coeff_c})")

    rhs_code = " + ".join(rhs_const) if rhs_const else "0"
    rhs_code = _substitute_params(rhs_code, ir)
    lb, ub = _bounds_from_op(op, rhs_code)

    lines.append(f"{indent}all_row_lower.append({lb})")
    lines.append(f"{indent}all_row_upper.append({ub})")
    lines.append(f"{indent}all_indices.extend(row_idx)")
    lines.append(f"{indent}all_values.extend(row_val)")
    lines.append(f"{indent}starts.append(len(all_indices))")

    lines.append("    n_cons = len(all_row_lower)")
    lines.append("    if n_cons > 0:")
    lines.append("        h.addRows(n_cons, np.array(all_row_lower), np.array(all_row_upper),")
    lines.append("                  len(all_indices), np.array(starts, dtype=np.int32),")
    lines.append("                  np.array(all_indices, dtype=np.int32),")
    lines.append("                  np.array(all_values, dtype=np.float64))")

    return lines


def _gen_single_constraint_with_lag(lhs_str: str, op: str, rhs_str: str,
                                     constraint: Constraint, ir: IR) -> list[str]:
    """Generate a single constraint that references specific indices (like t=0)."""
    lines = []

    # This handles constraints like: Inv[0] == I_init + x[0] - d[0]
    lines.append("    row_indices = []")
    lines.append("    row_values = []")

    # Parse to find variable references with literal indices
    lhs_terms = _extract_linear_terms_literal(lhs_str, ir)
    rhs_terms = _extract_linear_terms_literal(rhs_str, ir)

    all_var_terms = lhs_terms["var_terms"] + [(_negate(c), v, vi) for c, v, vi in rhs_terms["var_terms"]]
    rhs_const = rhs_terms["const_terms"] + [f"-({c})" for c in lhs_terms["const_terms"]]

    for coeff, vname, vindices in all_var_terms:
        offset = _offset_expr(vname, ir)
        flat = _flat_index_expr(vname, vindices, ir)
        coeff_c = _coeff_code(coeff, ir)
        lines.append(f"    row_indices.append({offset} + {flat})")
        lines.append(f"    row_values.append({coeff_c})")

    rhs_code = " + ".join(rhs_const) if rhs_const else "0"
    rhs_code = _substitute_params(rhs_code, ir)
    lb, ub = _bounds_from_op(op, rhs_code)

    lines.append(f"    row_lower = np.array([{lb}])")
    lines.append(f"    row_upper = np.array([{ub}])")
    lines.append("    starts = np.array([0, len(row_indices)], dtype=np.int32)")
    lines.append("    h.addRows(1, row_lower, row_upper, len(row_indices),")
    lines.append("              starts, np.array(row_indices, dtype=np.int32),")
    lines.append("              np.array(row_values, dtype=np.float64))")

    return lines


# ---------------------------------------------------------------------------
# Linear term extraction
# ---------------------------------------------------------------------------

def _extract_linear_terms(expr_str: str, ir: IR) -> dict:
    """Extract variable terms and constant terms from an expression.

    Returns dict with:
      var_terms: list of (coeff, var_name, var_indices, iterators)
      const_terms: list of code strings
    """
    expr_str = expr_str.strip()
    var_terms = []
    const_terms = []

    # Handle sum(...) expressions
    sums = _split_additive_terms(expr_str)
    for sign, term in sums:
        term = term.strip()
        m = re.match(r'sum\((.+)\)', term, re.DOTALL)
        if m:
            inner = m.group(1)
            body, iterators = _split_body_and_iterators(inner)
            parsed_iters = []
            for it in iterators:
                parts = it.strip().split(" in ")
                parsed_iters.append((parts[0].strip(), parts[1].strip()))

            coeff, vname, vindices = _parse_product(body, ir)
            if vname in ir.variables:
                effective_coeff = coeff if sign == "+" else _negate(coeff)
                var_terms.append((effective_coeff, vname, vindices, parsed_iters))
            else:
                effective = term if sign == "+" else f"-({term})"
                const_terms.append(effective)
        elif _has_var_reference(term, ir):
            # Direct variable reference like x[i,j] or M * z[t]
            coeff, vname, vindices = _parse_product(term, ir)
            if vname in ir.variables:
                effective_coeff = coeff if sign == "+" else _negate(coeff)
                var_terms.append((effective_coeff, vname, vindices, []))
            else:
                effective = term if sign == "+" else f"-({term})"
                const_terms.append(effective)
        else:
            effective = term if sign == "+" else f"-({term})"
            const_terms.append(effective)

    return {"var_terms": var_terms, "const_terms": const_terms}


def _extract_linear_terms_with_lags(expr_str: str, ir: IR) -> dict:
    """Like _extract_linear_terms but preserves lag info (t-1)."""
    expr_str = expr_str.strip()
    var_terms = []  # (coeff, var_name, var_indices, iterators, lag)
    const_terms = []

    sums = _split_additive_terms(expr_str)
    for sign, term in sums:
        term = term.strip()
        if _has_var_reference(term, ir):
            coeff, vname, vindices = _parse_product_with_lag(term, ir)
            if vname in ir.variables:
                lag = 0
                new_indices = []
                for idx in vindices:
                    m = re.match(r'(\w+)\s*-\s*(\d+)', idx)
                    if m:
                        new_indices.append(m.group(1))
                        lag = int(m.group(2))
                    else:
                        new_indices.append(idx)
                effective_coeff = coeff if sign == "+" else _negate(coeff)
                var_terms.append((effective_coeff, vname, new_indices, [], lag))
            else:
                effective = term if sign == "+" else f"-({term})"
                const_terms.append(effective)
        else:
            effective = term if sign == "+" else f"-({term})"
            const_terms.append(effective)

    return {"var_terms": var_terms, "const_terms": const_terms}


def _extract_linear_terms_literal(expr_str: str, ir: IR) -> dict:
    """Extract terms with literal indices (like x[0], d[0])."""
    expr_str = expr_str.strip()
    var_terms = []  # (coeff, var_name, var_indices)
    const_terms = []

    sums = _split_additive_terms(expr_str)
    for sign, term in sums:
        term = term.strip()
        if _has_var_reference(term, ir):
            coeff, vname, vindices = _parse_product(term, ir)
            if vname in ir.variables:
                effective_coeff = coeff if sign == "+" else _negate(coeff)
                var_terms.append((effective_coeff, vname, vindices))
            else:
                effective = term if sign == "+" else f"-({term})"
                const_terms.append(effective)
        else:
            effective = term if sign == "+" else f"-({term})"
            const_terms.append(effective)

    return {"var_terms": var_terms, "const_terms": const_terms}


def _split_additive_terms(expr: str) -> list[tuple[str, str]]:
    """Split expression into [(sign, term), ...] respecting parentheses and brackets."""
    terms = []
    depth = 0
    current = []
    sign = "+"
    i = 0
    while i < len(expr):
        ch = expr[i]
        if ch in '([':
            depth += 1
            current.append(ch)
        elif ch in ')]':
            depth -= 1
            current.append(ch)
        elif (ch == '+' or ch == '-') and depth == 0 and current:
            terms.append((sign, "".join(current).strip()))
            sign = ch if ch == '-' else '+'
            current = []
        else:
            current.append(ch)
        i += 1
    if current:
        terms.append((sign, "".join(current).strip()))
    return [(s, t) for s, t in terms if t]


def _has_var_reference(term: str, ir: IR) -> bool:
    """Check if term references any variable."""
    for vname in ir.variables:
        if re.search(rf'\b{re.escape(vname)}\b', term):
            return True
    return False


def _parse_product_with_lag(body: str, ir: IR) -> tuple[str, str, list[str]]:
    """Like _parse_product but handles lag expressions like Inv[t-1]."""
    body = body.strip()
    # Replace t-1 temporarily for AST parsing: Inv[t-1] isn't valid Python subscript
    # We handle it by regex
    m = re.match(r'(\w+)\[([^\]]+)\]', body)
    if m:
        name = m.group(1)
        idx_str = m.group(2)
        indices = [x.strip() for x in idx_str.split(',')]
        if name in ir.variables:
            return "1", name, indices
    # Try AST-based parsing for products like M * z[t]
    try:
        return _parse_product(body, ir)
    except SyntaxError:
        return body, "_unknown", []


def _negate(coeff: str) -> str:
    if coeff == "1":
        return "-1"
    if coeff == "-1":
        return "1"
    if coeff.startswith("-"):
        return coeff[1:]
    return f"-({coeff})"


def _bounds_from_op(op: str, rhs_code: str) -> tuple[str, str]:
    """Return (lower_bound, upper_bound) expressions for a comparison."""
    if op == "<=":
        return "-np.inf", rhs_code
    elif op == ">=":
        return rhs_code, "np.inf"
    elif op == "==":
        return rhs_code, rhs_code
    raise ValueError(f"Unknown operator: {op}")


def _substitute_params(code: str, ir: IR) -> str:
    """Replace parameter names with data dict lookups."""
    for pname in sorted(ir.parameters.keys(), key=len, reverse=True):
        param = ir.parameters[pname]
        if param.indices:
            # Indexed params: c[i,j] -> data["c"][i,j]
            code = re.sub(
                rf'\b{re.escape(pname)}\[([^\]]+)\]',
                f'data["{pname}"][\\1]',
                code,
            )
        else:
            # Scalar params: W -> data["W"]
            code = re.sub(rf'\b{re.escape(pname)}\b', f'data["{pname}"]', code)
    return code


# ---------------------------------------------------------------------------
# Solve + report + main
# ---------------------------------------------------------------------------

def _solve_and_report(ir: IR) -> str:
    lines = [
        'def solve_and_report(h: highspy.Highs, data: dict):',
        '    h.run()',
        '    status = h.getInfoValue("primal_solution_status")[1]',
        '    obj = h.getInfoValue("objective_function_value")[1]',
        '    sol = np.array(h.getSolution().col_value)',
        '',
    ]

    # Define set sizes in this function too
    for sname in ir.sets:
        lines.append(f'    n_{sname.lower()} = len(data["{sname}"])')
    lines.append('')

    lines.append('    status_str = "optimal" if status == 2 else str(int(status))')
    lines.append('    print(f"Status: {status_str}")')
    lines.append('    print(f"Objective: {obj:.4f}")')
    lines.append('    print("Solution:")')

    # Print solution for each variable group
    for vname, var in ir.variables.items():
        size_expr = _var_size_expr(var, ir)
        offset = _offset_expr(vname, ir)
        if var.indices:
            set_sizes = [f"n_{s.lower()}" for s in var.indices]
            idx_names = [s.lower() for s in var.indices]
            shape = ", ".join(set_sizes)
            lines.append(f'    {vname}_sol = sol[{offset}:{offset} + {size_expr}].reshape({shape})')

            # Nested loop to print nonzero values
            indent = "    "
            for idx, sname in zip(idx_names, var.indices):
                lines.append(f'{indent}for {idx} in range(n_{sname.lower()}):')
                indent += "    "

            idx_str = ", ".join(idx_names)
            # Build label with string concatenation to avoid nested f-string issues
            label_parts = []
            for idx, sname in zip(idx_names, var.indices):
                label_parts.append(f'str(data["{sname}"][{idx}])')
            label_expr = ' + "," + '.join(label_parts)
            lines.append(f'{indent}val = {vname}_sol[{idx_str}]')
            lines.append(f'{indent}if abs(val) > 1e-6:')
            lines.append(f'{indent}    label = {label_expr}')
            lines.append(f'{indent}    print(f"  {vname}[{{label}}] = {{val:.4f}}")')
        else:
            lines.append(f'    val = sol[{offset}]')
            lines.append(f'    print(f"  {vname} = {{val:.4f}}")')

    return "\n".join(lines)


def _main() -> str:
    return '''if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("data", help="Path to data file (YAML or JSON)")
    args = parser.parse_args()

    data = load_data(args.data)
    h = build_model(data)
    solve_and_report(h, data)'''
